
dataset_args:
    dataset_path: PNLPhub/FarsInstruct
    streaming: false

model_args:
    model_path: ../lora_checkpoints/lim_cocola_19
    tokenizer_path: ../lora_checkpoints/lim_cocola_19
    vocab_size: 42001

training_args:
    run_name: #Set your run name 
    datasets: SajjadAyoubi/persian_qa,PNLPhub/digikala-sentiment-analysis,PNLPhub/DigiMag,PNLPhub/C-ExaPPC,PNLPhub/Pars-ABSA,parsinlu_reading_comprehension,persiannlp/parsinlu_sentiment,PNLPhub/Persian-News,pn_summary,SLPL/syntran-fa,wiki_summary,p3_xlwic
    # datasets: wiki_summary
    instruction_template: ava
    shots: 1
    seed: 557
    pin_memory: true
    buffer_size: 10000
    max_len: 512
    output_dir: ./results/lim_cocola_20
    # evaluation_strategy: "steps"
    num_train_epochs: 5
    max_steps: -1
    save_steps: 10
    logging_steps: 50
    # logging_dir: /home/hojjat/workstation/tensorboardlog
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 1
    learning_rate: 0.0006
    optim: paged_adamw_8bit
    lr_scheduler_type: linear
    warmup_steps: 1
    gradient_checkpointing: false
    bf16: false
    fp16: true
    weight_decay: 0.07
    ddp_find_unused_parameters: False


evaluation_args:
    run_name: cola_19
    tokenizer_path: lora_checkpoints/lim_cocola_20
    model_path: lora_checkpoints/lim_cocola_20
    model_type: causal
    peft_model_id: null

    # model_path: /mnt/beegfs/wrkdir/u111187/Hojjat_Workstation/FarsInstruct/lora_checkpoints/lim_cocola_20
    # model_type: causal
    # peft_model_id: null

    datasets: PNLPhub/FarsTail,PNLPhub/snappfood-sentiment-analysis,persiannlp/parsinlu_query_paraphrasing,persiannlp/parsinlu_entailment
    # datasets: persiannlp/parsinlu_entailment
    #datasets: null
    instruction_template: ava
    shots: 1
    task_type: 'generate_until'
    batch_size: 1
    max_len: 128

quantization_args:
    load_in_4bit: false
    double_quant: true
    quant_type: "nf4"
    lora_rank: 8
    lora_alpha: 16
    lora_dropout: 0.05 
