dataset_args:
  dataset_path: 'hojjat-m/FarsInstruct'
  streaming: false

model_args:
  model_path: 'HooshvareLab/gpt2-fa'
  vocab_size: 42001

training_args:
  lr: 0.001
  seed: 32
  batch_size: 8
  scheduler_step: 10000
  epochs: 2
  pin_memory: false
  buffer_size: 10000
  max_len: 256
